language: node_js
node_js:
  - "10.21"

install:
  - npm i

script:
  - npm run build

branches:
  only:
  - master
  - release
  - development
  
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  tag: latest
  on:
    branch: master
